name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello Full Stack Open!"
      - name: What date and time is it
        run: |
          date
      - name: Show me directory content
        run: |
          ls -ltr
